twitSent/urls.py
from django.conf.urls import url,include

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls')),
]

website/urls.py
from django.conf.urls import url,include

from . import views

app_name='website'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^new/', views.form_data, name='new'),
]

website/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError

import os
import requests

import tweepy
from textblob import TextBlob

### For Logging purposes to console.. disable in production
# import logging
# logger = logging.getLogger(__name__)

def twitterHero(data,size):
    consumer_key='iFbr9Dutq6HUI0j1MAdjV0klm'
    consumer_secret='XcLBu7YxFCgZF20CfOouXh2ysMU2YZOSAtk6zh6HJZ0bFBrgW2'

    access_token='1109145293004525568-QpzoUMP4t13r95qHZOSwUCtZqYywWM'
    access_token_secret='HD24hwb2pnMIz1OJVe3YjYRvxsNrEuUTgkHzx1C9ZML0h'

    auth=tweepy.OAuthHandler(consumer_key,consumer_secret)
    auth.set_access_token(access_token,access_token_secret)

    api=tweepy.API(auth)

    S=[]
    counter=[0,0,0] # positive, negative, neutral
    for tweet in tweepy.Cursor(api.search, q=data, rpp=100, count=20, result_type="recent", include_entities=True, lang="en").items(size):
        # logger.log(100,tweet)  # MASSIVE DATA DUMP for debugging
        analysis=TextBlob(tweet.text)
        if analysis.sentiment.polarity > 0:
            res='positive'
            counter[0]+=1
        elif analysis.sentiment.polarity == 0:
            res='neutral'
            counter[2]+=1
        else:
            res='negative'
            counter[1]+=1
        S.append((tweet.text,analysis.sentiment,res,tweet.user.name,tweet.user.profile_image_url_https,tweet.user.screen_name))
    positivePer=(counter[0]/size)*100
    negativePer=(counter[1]/size)*100
    neutralPer=(counter[2]/size)*100
    S.append((positivePer,negativePer,neutralPer))
    return S


def index(request):
    return render(request,'website/home.html',{})


def form_data(request):
    try:
        data=request.POST['q']
        size=int(request.POST['size'])
    except MultiValueDictKeyError:
        data='data science'
        size=50
    if data=='':
        data='data science'
    S=twitterHero(data,size)
    # logger.log(100,"Called function.")
    posPer,negPer,ntrPer=S[-1][0],S[-1][1],S[-1][2]
    del S[-1]
    return render(request,'website/index.html',{'data':S,'search':data,'posPer':posPer,'negPer':negPer,'ntrPer':ntrPer})

website/templates/website/base.html
 
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'website/images/favicon.png' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
  <link href="{% static 'website/css/style.css' %}" rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  {% block meta %}{% endblock %}
</head>
<body>
  <div class="fullscreen-bg">
      <video loop muted autoplay poster="{% static 'website/images/videoframe.jpg' %}" class="fullscreen-bg__video">
          <source src="{% static 'website/images/video.webm' %}" type="video/webm">
      </video>
  </div>
  <br>
  {% block search %}{% endblock %}
  <div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
  {% block result %}{% endblock %}


{% block graph %}{% endblock %}

</body>
</html>

website/templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Sentiment Analysis{% endblock %}

{% block meta %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" />
<!--[if lt IE 9]>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.ie.min.css" />
<![endif]-->
<link href="{% static 'website/css/grumble.min.css' %}" rel='stylesheet' type='text/css'>
<script src="{% static 'website/js/jquery.grumble.min.js' %}"></script>
{% endblock %}

{% block search %}
<div class="parent">
  <div style="font-family: 'Satisfy',cursive;margin:auto;text-align: center;"><h1>Twitter Sentiment Analysis</h1></div>
    <br>
    <div class="container col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
      <form action="{% url 'website:new' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div id="inputDiv">
            <input type="text" name="q" placeholder="data science" class="form-control" style="text-align:center;width:90%;">
            <select class="form-control" style="width:10%;padding:0;" name="size" id="tour" data-angle="130">
              <option value="25">25</option>
              <option value="50" selected>50</option>
              <option value="100">100</option>
              <option value="200">200</option>
            </select>
          </div>

          <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2" style="margin-top:10px;"><input type="submit" value="Submit" class="btn btn-default" style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Clear" class="btn btn-default" style="float:right;"></div>
        </div>
      </form>
    </div>
    <div class="clearfix"></div>
</div>
<a class="github-fork-ribbon right-bottom hidden-xs" href="https://github.com/ arihantjain8118" target="_blank" title="@ arihantjain8118">@ arihantjain8118</a>
{% endblock %}

{% block graph %}
<script>
var number = Math.floor(Math.random() * (2000 - 1000 + 1)) + 1000;
  $(function(){
    $('#tour').grumble({
    		text: 'Select the number of tweets to load.',
    		angle: 130,
    		distance: 3,
    		showAfter: number,
    		hideAfter: 3000
  	});
  });
</script>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block title %}Sentiment Analysis on {{search}}{% endblock %}

{% block meta %}
<script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock %}

{% block search %}
<div style="font-family: 'Satisfy',cursive;margin:auto;text-align: center;"><h1>Twitter Sentiment Analysis</h1></div>
  <br>
  <div class="container col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <form action="{% url 'website:new' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <div id="inputDiv">
          <input type="text" name="q" placeholder="search topic.." class="form-control" style="text-align:center;width:90%;" required>
          <select class="form-control" style="width:10%;padding:0;" name="size">
            <option value="25">25</option>
            <option value="50" selected>50</option>
            <option value="100">100</option>
            <option value="200">200</option>
          </select>
        </div>

        <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2" style="margin-top:10px;"><input type="submit" value="Submit" class="btn btn-default" style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Clear" class="btn btn-default" style="float:right;"></div>
      </div>
    </form>
  </div>
  <div class="clearfix"></div>
  <br>
{% endblock %}

{% block result %}
<br><br>
  {% if data %}
    <div class="container-fluid col-md-10 col-md-offset-1">
      {% for x in data %}
        {% if x.2 == 'positive' %}
          <div class="alert alert-success" role="alert"><img src="{{x.4}}" alt="image" class="img-circle">&nbsp;&nbsp;<strong><a href="https://www.twitter.com/{{x.5}}" target="_blank">{{x.3}}</a>:</strong> {{x.0 | safe}}</div>
        {% elif x.2 == 'negative' %}
          <div class="alert alert-danger" role="alert"><img src="{{x.4}}" alt="image" class="img-circle">&nbsp;&nbsp;<strong><a href="https://www.twitter.com/{{x.5}}" target="_blank">{{x.3}}</a>:</strong> {{x.0 | safe}}</div>
        {% else %}
          <div class="alert alert-info" role="alert"><img src="{{x.4}}" alt="image" class="img-circle">&nbsp;&nbsp;<strong><a href="https://www.twitter.com/{{x.5}}" target="_blank">{{x.3}}</a>:</strong> {{x.0 | safe}}</div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="clearfix"></div>
    <div style="width:100%;height:20px;color:#7c7b7b;text-align:center;">Copyright &copy; <a href="https://arihantjain8118.github.io/portfolio/" style="color: inherit;" target="_blank">Arihant Jain</a></div>
  {% endif %}
{% endblock %}



{% block graph %}
<script>
{% if data %}{% endif %}
  $(function () {
    Highcharts.chart('container', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            backgroundColor:'rgba(255, 255, 255, 0.1)'
        },
        title: {
            text: ''
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        credits: {
          enabled: false
        },
        series: [{
            name: 'Tweets',
            colorByPoint: true,
            data: [{
                name: 'Neutral',
                y: {{ntrPer}}
            }, {
                name: 'Negative',
                y: {{negPer}}
            }, {
                name: 'Positive',
                y: {{posPer}},
                sliced: true,
                selected: true
            }]
        }]
    });
  });
</script>
{% endblock %}